[workspace]
resolver = "2"
members = ["crates/eyrie"]

[workspace.package]
repository = "https://github.com/oneofthezombies/eyrie"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["oneofthezombies hunhoekim@gmail.com"]
